test_flask_lesson/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    comment_text = StringField('Text', validators=[DataRequired()])
    submit = SubmitField('Comment')

test_flask_lesson/posts/routes.py
from flask import render_template, url_for, flash, \
                  redirect, request, abort, Blueprint
from flask_login import current_user, login_required

from test_flask_lesson import db
from test_flask_lesson.models import Post, Comment, Like
from test_flask_lesson.posts.forms import PostForm, CommentForm


posts = Blueprint('posts', __name__)

@posts.route('/allposts')
@login_required
def allposts():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).\
            paginate(page=page, per_page=5)
    return render_template('allposts.html', posts=posts)

@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(
            text=form.comment_text.data,
            post_id=post_id,
            username=current_user.username
        )
        db.session.add(comment)
        db.session.commit()
        flash('Your comment added!', 'success')
        return redirect(f'/post/{post_id}')
    return render_template(
        'post.html',
        title=post.title,
        post=post,
        form=form
    )

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            content=form.content.data,
            author=current_user
        )
        db.session.add(post)
        db.session.commit()
        flash('Your post was created!', 'success')
        return redirect(url_for('posts.allposts'))
    return render_template(
        'create_post.html',
        title='New post',
        form=form,
        legend='New post'
    )

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post was updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template(
        'create_post.html',
        title='Updatte post',
        form=form,
        legend='Update post'
    )

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post was deleted!', 'success')
    return redirect(url_for('posts.allposts'))

@posts.route("/comment/<int:comment_id>/delete", methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.username != current_user.username:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Your comment was deleted', 'success')
    return redirect(f'/post/{comment.post_id}')

@posts.route("/post/<int:post_id>/like")
@login_required
def like_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author == current_user:
        abort(403)
    like = Like(
        post_id=post_id,
        username=current_user.username
    )
    db.session.add(like)
    db.session.commit()
    flash('Your like was added!', 'success')
    return redirect(url_for('posts.post', post_id=post_id))

test_flask_lesson/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from test_flask_lesson import db, bcrypt
from test_flask_lesson.models import User, Post
from test_flask_lesson.users.utils import save_picture, send_reset_email
from test_flask_lesson.users.forms import RegistrationForm, LoginForm, \
    UpdateAccountForm, ResetPasswordForm, \
    RequestResetPasswordForm

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data). \
            decode('utf-8')
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=hashed_password,
            role=form.role.data
        )
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись успешно создана!', 'success')
        return redirect(url_for("main.home"))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.allposts'))
        else:
            flash('Войти не удалось. Проверьте email и пароль!', 'attention')
    return render_template('login.html', title='Authentication', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт успешно обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=form.username.data).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted).paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form, posts=posts, user=user)

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    form = RequestResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('We send reset password message to your email.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('This is not a valid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password updated! Now ypu can login', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset password', form=form)

test_flask_lesson/templates/account.html
{% extends "base.html" %}
{% block content %}
    {% include 'includes/inc_header.html'%}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>

      <form method="POST" action="" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset>
              <legend><h3>User Profile</h3></legend>
              <div class="6u 12u(3)">
                  {{ form.username.label() }}

                  {% if form.username.errors %}
                      {{ form.username() }}
                      <div class="invalid-feedback">
                          {% for error in form.username.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.username() }}
                  {% endif %}
              </div>
              <div class="6u 12u(3)">
                  {{ form.email.label() }}
                  {% if form.email.errors %}
                      {{ form.email() }}
                      <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.email() }}
                  {% endif %}
              </div>
              <div class="6u 12u(3)">
                  {{ form.picture.label() }}
                  {{ form.picture() }}
                  {% if form.picture.errors %}
                      {% for error in form.picture.errors %}
                          <span class="danger">{{ error }}</span></br>
                      {% endfor %}
                  {% endif %}
              </div>
          </fieldset>
          <div class="12u">
              {{ form.submit(class="button") }}
          </div>
      </form>      
    </div>   
{% endblock content %}

test_flask_lesson/templates/allposts.html
{% extends "base.html" %}
{% block content %}
    {% include 'includes/inc_header.html'%}
  {% for post in posts.items %}
  <div style="display: flex;">
    <article style="display: flex; flex-direction: column;"> 
      <img style="margin-right: 5px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <a href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author" style="margin: 0 auto;">{{ post.author.username }}</a>
    </article>
    
    <div style="margin-bottom: 20px;">
      <div>
        <h4><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>

        <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
        <br>
        <br>
        <p>{{ post.content }}</p>
      </div>
      <!-- <div class="card-footer" style="font-size: 20px;">
        <i class="fa fa-heart-o"></i>
        <i class="fa fa-bookmark-o"></i>
      </div> -->
    </div>
  </div>
  {% endfor %}

  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="button" href="{{ url_for('posts.allposts', page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="button" href="{{ url_for('posts.allposts', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
{% endblock content %}

test_flask_lesson/templates/base.html
<!DOCTYPE HTML>

<html>
	<head>
		<title> </title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<!--[if lte IE 8]><script src="css/ie/html5shiv.js"></script><![endif]-->
		<script src="/static/js/jquery.min.js"></script>
		<script src="/static/js/jquery.dropotron.min.js"></script>
		<script src="/static/js/jquery.scrollgress.min.js"></script>
		<script src="/static/js/jquery.scrolly.min.js"></script>
		<script src="/static/js/jquery.slidertron.min.js"></script>
		<script src="/static/js/skel.min.js"></script>
		<script src="/static/js/skel-layers.min.js"></script>
		<script src="/static/js/init.js"></script>
		<noscript>
			<link rel="stylesheet" href="/static/css/skel.css" />
            <link rel="stylesheet" href="/static/css/style.css" />
			<link rel="stylesheet" href="/static/css/style-xlarge.css" />
		</noscript>
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie/v9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
	</head>
    {% block content %}{% endblock %}
    </body>
</html>

test_flask_lesson/templates/create_post.html
{% extends "base.html" %}
{% block content %}
    {% include 'includes/inc_header.html'%}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend class=><h3>{{ legend }}</h3></legend>
            <div class="6u 12u(3)">
                {{ form.title.label() }}
                {% if form.title.errors %}
                    {{ form.title() }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title() }}
                {% endif %}
            </div>
            <div class="6u 12u(3)">
                {{ form.content.label() }}
                {% if form.content.errors %}
                    {{ form.content() }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content() }}
                {% endif %}
            </div>
        </fieldset>
        <div class="12u">
            {{ form.submit(class="button") }}
        </div>
    </form>
</div>
{% endblock content %}

test_flask_lesson/templates/left-sidebar.html
<!DOCTYPE HTML>

<html>
	<head>
		<title> </title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<!--[if lte IE 8]><script src="css/ie/html5shiv.js"></script><![endif]-->
		<script src="/static/js/jquery.min.js"></script>
		<script src="/static/js/jquery.dropotron.min.js"></script>
		<script src="/static/js/jquery.scrollgress.min.js"></script>
		<script src="/static/js/jquery.scrolly.min.js"></script>
		<script src="/static/js/jquery.slidertron.min.js"></script>
		<script src="/static/js/skel.min.js"></script>
		<script src="/static/js/skel-layers.min.js"></script>
		<script src="/static/js/init.js"></script>
		<noscript>
			<link rel="stylesheet" href="/static/css/skel.css" />
			<link rel="stylesheet" href="/static/css/style.css" />
			<link rel="stylesheet" href="/static/css/style-xlarge.css" />
		</noscript>
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie/v9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
	</head>
	<body>

		<!-- Header -->
			<header id="header" class="skel-layers-fixed">
			<h1><a href="index.html">HTML5 Website <span>by Html5webtemplates.co.uk</span></a></h1>	
				<nav id="nav">
					<ul>
						<li><a href="index.html">Home</a></li>
						<li>
							<a href="" class="icon fa-angle-down">Layouts</a>
							<ul>
								<li><a href="left-sidebar.html">Left Sidebar</a></li>
								<li><a href="right-sidebar.html">Right Sidebar</a></li>
								<li><a href="no-sidebar.html">No Sidebar</a></li>
								<li>
									<a href="">Submenu</a>
									<ul>
										<li><a href="#">Option 1</a></li>
										<li><a href="#">Option 2</a></li>
										<li><a href="#">Option 3</a></li>
										<li><a href="#">Option 4</a></li>
									</ul>
								</li>
							</ul>
						</li>
						<li><a href="elements.html">Elements</a></li>
					</ul>
				</nav>
			</header>

		<!-- Main -->
			<section id="main" class="wrapper style1">
				<header class="major">
					<h2>Left Sidebar</h2>
					<p>Faucibus neque adipiscing mi lorem semper blandit</p>
				</header>
				<div class="container">
					<div class="row 150%">
						<div class="4u 12u$(2)">
						
							<!-- Sidebar -->
								<section id="sidebar">
									<section>
										<h3>Magna Feugiat</h3>
										<p>Sed tristique purus vitae volutpat commodo suscipit amet sed nibh. Proin a ullamcorper sed blandit. Sed tristique purus vitae volutpat commodo suscipit ullamcorper commodo suscipit amet sed nibh. Proin a ullamcorper sed blandit..</p>
										<footer>
											<ul class="actions">
												<li><a href="#" class="button small alt">Learn More</a></li>
											</ul>
										</footer>
									</section>
									<hr />
									<section>
										<a href="#" class="image fit"><img src="/static/images/pic02.jpg" alt="" /></a>
										<h3>Amet Lorem Tempus</h3>
										<p>Sed tristique purus vitae volutpat commodo suscipit amet sed nibh. Proin a ullamcorper sed blandit. Sed tristique purus vitae volutpat commodo suscipit ullamcorper sed blandit lorem ipsum dolore.</p>
										<footer>
											<ul class="actions">
												<li><a href="#" class="button small alt">Learn More</a></li>
											</ul>
										</footer>
									</section>
								</section>

						</div>
						<div class="8u 12u$(2) important(2)">
						
							<!-- Content -->
								<section id="content">
									<a href="#" class="image fit"><img src="/static/images/slide02.jpg" alt="" /></a>
									<h3>Dolore Amet Consequat</h3>
									<p>Aliquam massa urna, imperdiet sit amet mi non, bibendum euismod est. Curabitur mi justo, tincidunt vel eros ullamcorper, porta cursus justo. Cras vel neque eros. Vestibulum diam quam, mollis at magna consectetur non, malesuada quis augue. Morbi tincidunt pretium interdum est. Curabitur mi justo, tincidunt vel eros ullamcorper, porta cursus justo. Cras vel neque eros. Vestibulum diam.</p>
									<h3>Sed Magna Ornare</h3>
									<p>In vestibulum massa quis arcu lobortis tempus. Nam pretium arcu in odio vulputate luctus. Suspendisse euismod lorem eget lacinia fringilla. Sed sed felis justo. Nunc sodales elit in laoreet aliquam. Nam gravida, nisl sit amet iaculis porttitor, risus nisi rutrum metus.</p>
									<ul>
										<li>Faucibus orci lobortis ac adipiscing integer.</li>
										<li>Col accumsan arcu mi aliquet placerat.</li>
										<li>Lobortis vestibulum ut magna tempor massa nascetur.</li>
										<li>Blandit massa non blandit tempor interdum.</li>
										<li>Lacinia mattis arcu nascetur lobortis.</li>
									</ul>
								</section>
								
						</div>
					</div>
				</div>
			</section>
			
		<!-- Footer -->
			<footer id="footer">
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
					<li><a href="#" class="icon fa-envelope"><span class="label">Envelope</span></a></li>
				</ul>
				<ul class="menu">
					<li><a href="#">FAQ</a></li>
					<li><a href="#">Terms of Use</a></li>
					<li><a href="#">Privacy</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
				<span class="copyright">
				&copy; Copyright. All rights reserved. Design by <a href="http://www.html5webtemplates.co.uk">Responsive Web Templates</a>	
				</span>
			</footer>

	</body>
</html>

test_flask_lesson/templates/login.html
{% extends "base.html" %}
{% block content %}
    {% include 'includes/inc_header.html'%}
    <!-- Form user login -->
    <section>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend><h3>Authorization</h3></legend>
                <div class="6u 12u(3)">
                    {{ form.email.label() }}
                    {% if form.email.errors %}
                        {{ form.email() }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email() }}
                    {% endif %}
                </div>
                <div class="6u 12u(3)">
                    {{ form.password.label() }}
                    {% if form.password.errors %}
                        {{ form.password() }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password() }}
                    {% endif %}
                </div>
                <div class="6u 12u(3)">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="12u">
                {{ form.submit(class="button") }}
                <small>
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
            <small style="font-size: 15px; font-weight: 500;">
                Do you need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
            </small>
        </form>
    </section>
{% endblock content %}

test_flask_lesson/templates/post.html
{% extends "base.html" %}
{% block content %}
    {% include 'includes/inc_header.html'%}
<div style="display: flex;">
  <article style="display: flex; flex-direction: column;"> 
    <img style="margin-right: 5px; width: 150px; height: 150px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <a href="{{ url_for('users.user_posts', username=post.author.username) }}" style="margin: 0 auto">{{ post.author.username }}</a>
  </article>
  
  <div style="margin-bottom: 20px;">
    <div>
      <h4>{{ post.title }}</h4>
      <small>Published {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
      <br>
      <br>
      <p>{{ post.content }}</p>
    </div>
    <div style="font-size: 20px;">
      <!-- <i class="fa fa-heart-o"></i>
      <i class="fa fa-bookmark-o"></i> -->
      {% if post.author == current_user %}
        <div style="font-size: 20px;">
            {% if post.author == current_user %}
                <a href="{{url_for('posts.update_post', post_id=post.id) }}">Update</a>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="button" type="submit" value="Delete">
                </form>
                <!-- <a href="{{url_for('posts.delete_post', post_id=post.id) }}">Delete</a>
            <button type="button" data-toggle="modal" data-target="#deleteModal">Delete</button> -->
            {% endif %}
        </div>
      {% endif %}
    </div>
    {% if post.comments %}
        <h2>Comments</h2>
        <p>
            {% for comment in post.comments | reverse %}
                <p>{{ comment.text }}</p>
                <p>
                    <small>Author: {{ comment.username }}</small>
                    <small>Date: {{ comment.timestamp.strftime('%A, %d %B %Y %I:%M %p') }}</small>
                </p>
                {% if comment.username == current_user.username %}
                    <form action="{{ url_for('posts.delete_comment', comment_id=comment.id) }}" method="POST">
                        <input class="submit" type="submit" value="Delete">
                    </form>
                {% endif %}
                <hr>
                {% endfor %}
    {% endif %}
    <div class="likes">
        <a href="{{ url_for('posts.like_post', post_id=post.id) }}" class="button">Like</a>
        <p>{{ post.likes.count() }}</p>
    </div>
    <div>
        <h2>Leave comment</h2>
        <form action="{{ url_for('posts.post', post_id=post.id) }}", method="POST">
            {{ form.hidden_tag() }}
        <fieldset>
            <div class="6u 12u(3)">
                {{ form.comment_text() }}
            </div>
        </fieldset>
        <div class="12u">
            {{ form.submit(class="button") }}
        </div>
    </div>
  </div>
</div>
  
<!-- Modal -->
<!--
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-title">
          <h5 class="modal-title" id="deleteModalLabel">Delette post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
-->
{% endblock content %}

test_flask_lesson/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend>Сброс пароля</legend>
                <div class="6u 12u(3)">
                    {{ form.email.label() }}
                    {% if form.email.errors %}
                        {{ form.email() }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email() }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="12u">
                {{ form.submit(class="button") }}
            </div>
        </form>
    </div>
{% endblock content %}

test_flask_lesson/templates/reset_token.html
{% extends "base.html" %}
{% block content %}
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="6u 12u(3)">
                <legend>Сброс пароля</legend>
                <div class="6u 12u(3)">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="6u 12u(3)">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="12u">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

test_flask_lesson/templates/user_posts.html
{% extends "base.html" %}
{% block content %}
    {% include 'includes/inc_header.html'%}
    <h1>Посты опубликованы пользователем {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
    <div style="display: flex;">
      <article style="display: flex; flex-direction: column;"> 
        <img style="margin-right: 5px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}" style="margin: 0 auto">{{ post.author.username }}</a>
      </article>
      
      <div style="margin-bottom: 20px;">
        <div>
          <h4><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>

          <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
          <br>
          <br>
          <p>{{ post.content }}</p>
        </div>
        <!-- <div class="card-footer" style="font-size: 20px;">
          <i class="fa fa-heart-o"></i>
          <i class="fa fa-bookmark-o"></i>
        </div> -->
      </div>
    </div>
    {% endfor %}

    
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="button" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="button" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}