test_flask_lesson/main/routes.py
from flask import render_template, Blueprint
from test_flask_lesson.models import User


main = Blueprint("main", __name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template("index.html")

test_flask_lesson/posts/routes.py
from flask import render_template, url_for, flash, \
                  redirect, request, abort, Blueprint
from flask_login import current_user, login_required

from test_flask_lesson import db
from test_flask_lesson.models import Post, Comment, Like
from test_flask_lesson.posts.forms import PostForm, CommentForm


posts = Blueprint('posts', __name__)

@posts.route('/allposts')
@login_required
def allposts():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).\
            paginate(page=page, per_page=5)
    return render_template('allposts.html', posts=posts)

@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(
            text=form.comment_text.data,
            post_id=post_id,
            username=current_user.username
        )
        db.session.add(comment)
        db.session.commit()
        flash('Your comment added!', 'success')
        return redirect(f'/post/{post_id}')
    return render_template(
        'post.html',
        title=post.title,
        post=post,
        form=form
    )

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            content=form.content.data,
            author=current_user
        )
        db.session.add(post)
        db.session.commit()
        flash('Your post was created!', 'success')
        return redirect(url_for('posts.allposts'))
    return render_template(
        'create_post.html',
        title='New post',
        form=form,
        legend='New post'
    )

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post was updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template(
        'create_post.html',
        title='Updatte post',
        form=form,
        legend='Update post'
    )

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post was deleted!', 'success')
    return redirect(url_for('posts.allposts'))

@posts.route("/comment/<int:comment_id>/delete", methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.username != current_user.username:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Your comment was deleted', 'success')
    return redirect(f'/post/{comment.post_id}')

@posts.route("/post/<int:post_id>/like")
@login_required
def like_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author == current_user:
        abort(403)
    like = Like(
        post_id=post_id,
        username=current_user.username
    )
    db.session.add(like)
    db.session.commit()
    flash('Your like was added!', 'success')
    return redirect(url_for('posts.post', post_id=post_id))

test_flask_lesson/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from test_flask_lesson import db, bcrypt
from test_flask_lesson.models import User, Post
from test_flask_lesson.users.utils import save_picture, send_reset_email
from test_flask_lesson.users.forms import RegistrationForm, LoginForm, \
    UpdateAccountForm, ResetPasswordForm, \
    RequestResetPasswordForm

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data). \
            decode('utf-8')
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=hashed_password,
            role=form.role.data
        )
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись успешно создана!', 'success')
        return redirect(url_for("main.home"))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.allposts'))
        else:
            flash('Войти не удалось. Проверьте email и пароль!', 'attention')
    return render_template('login.html', title='Authentication', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт успешно обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=form.username.data).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted).paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form, posts=posts, user=user)

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    form = RequestResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('We send reset password message to your email.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('This is not a valid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password updated! Now ypu can login', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset password', form=form)

test_flask_lesson/templates/includes/inc_footer.html
<!-- Footer -->
<footer id="footer">
    <ul class="icons">
        <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
        <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
        <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
        <li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
        <li><a href="#" class="icon fa-envelope"><span class="label">Envelope</span></a></li>
    </ul>
    <ul class="menu">
        <li><a href="#">FAQ</a></li>
        <li><a href="#">Terms of Use</a></li>
        <li><a href="#">Privacy</a></li>
        <li><a href="#">Contact</a></li>
    </ul>
    <span class="copyright">
        &copy; Copyright. All rights reserved. Design by <a href="http://www.html5webtemplates.co.uk">Responsive Web Templates</a>
    </span>
</footer>

test_flask_lesson/templates/includes/inc_header.html
<!-- Header -->
<header id="header" class="alt skel-layers-fixed" style="background-color: #3d3b3c">
    <h1><a href="{{ url_for('main.home') }}"><span>This is the best blog EVER!:)</span></a></h1>
    <nav id="nav">
        <ul>
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li>
                <a href="" class="icon fa-angle-down">Layouts</a>
                <ul>
                    <li><a href="left-sidebar.html">Left Sidebar</a></li>
                    <li><a href="right-sidebar.html">Right Sidebar</a></li>
                    <li><a href="no-sidebar.html">No Sidebar</a></li>
                    <li>
                        <a href="">Submenu</a>
                        <ul>
                            <li><a href="#">Option 1</a></li>
                            <li><a href="#">Option 2</a></li>
                            <li><a href="#">Option 3</a></li>
                            <li><a href="#">Option 4</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('posts.allposts') }}">Posts</a></li>
                <li><a href="{{ url_for('posts.new_post') }}">New post</a></li>
                <li><a href="{{ url_for('users.account') }}">Profile</a></li>
                <li><a href="{{ url_for('users.logout') }}">Exit</a></li>            
                {% if current_user.role == 'admin' %}
                    <li><a href="{{ url_for('admin.index') }}">Go to admin!</a></li>
                {% endif %}
            {% else %}
                <li><a href="{{ url_for('users.login') }}">Login</a></li>
                <li><a href="{{ url_for('users.register') }}">Register</a></li>
            {% endif %}
        </ul>
    </nav>
</header>